#!/bin/bash

tab () {
/usr/bin/osascript <<-EOF
tell application "iTerm"
    make new terminal
    tell the current terminal
        activate current session
        launch session "Default Session"
        tell the last session
            write text "$1"
        end tell
    end tell
end tell
EOF
}

tab "cd /Users/jasonbenn/code/clinkle-web/member;bundle exec guard"
tab "cd /Users/jasonbenn/code/clinkle-web/member;bundle exec rake jasmine"
tab "cd /Users/jasonbenn/code/clinkle-web;subl;cd-fixture member"

open -a Google\ Chrome\ Canary.app http://www-dev/test-panel
open -a Google\ Chrome\ Canary.app http://localhost:8888/
open -a Google\ Chrome\ Canary.app http://www-dev/
